vich_uploader:
  db_driver: orm

  mappings:
    images:
      uri_prefix: /images
      upload_destination: "%kernel.project_dir%/public/images"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    profiles:
      uri_prefix: /images/profiles
      upload_destination: "%kernel.project_dir%/public/images/profiles"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
