vich_uploader:
  db_driver: orm
  storage: flysystem

  mappings:
    profiles:
      uri_prefix: /images/profiles
      upload_destination: default.storage
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true

    contacts:
      uri_prefix: /images/contacts
      upload_destination: aws.storage
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true
