version: "3.7"
services:
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ypsi_cloud_rh
    ports:
      - "44021:3306"
    networks:
      - dev

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: access1234
      MINIO_ROOT_PASSWORD: secret1234
    volumes:
      - data1-1:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

#  phpmyadmin:
#    image: phpmyadmin
#    container_name: phpmyadmin_docker_symfony_serveur
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 44022:80
#    environment:
#      PMA_HOST: database
#    networks:
#      - dev

volumes:
  data1-1:

networks:
  dev:
